### ISSUE TITLE
re: auto mirror integration in 2.79 ?

### ISSUE THREAD

**Issue by meta-androcto** [lapineige/Blender_add-ons#1]
hello, I would like to add auto mirror to Blender 2.79
Please let me know soon if it's ok.
Thanks for the great addons you make.

**Comment by lapineige** [comment]
Hello @meta-androcto 
It should works fine, just install it as any add-on :)

For your information, I kept this repo as a (probably unmaintained) mirror, but I'm now working on this one: https://framagit.org/Lapineige/Blender_add-ons
(for auto-mirror right now there was no update so there is no change)
Thanks for your interest in my add-ons :)

**Comment by albertogmx** [comment]
Hello Lapineige,
I confirm that this addon doesn't work with Blender 2.78c .

Can you do something about it ? it does look like a must have for modelers.
(I'm quitting 3ds max and learning Blender)

**Comment by albertogmx** [comment]
It now works ! I copied the text in a new .py file.

(before the install from file didn't work, no idea why)

sorry about that, thanks for the great work !

**Comment by lapineige** [comment]
I'm currently using it on Blender 2.78 (as well as a fresh 2.79 build) and it works well.
How did you save the file ? Did you just use the zip file from github ? (because it won't work)

Anyway, I'm happy to know that it works now. Enjoy :)
